### ISSUE TITLE
Broken .swf File

### ISSUE THREAD

**Issue by ghost** [Calvin304/Autosplit-FaW#1]
![image](https://user-images.githubusercontent.com/79287572/108431074-5e2d4380-7210-11eb-94a8-bfe840450847.png)

We can't keep going past level 2, no matter the order we complete the levels or reset the flash player or .swf file.

Other Light Temple .swf files work but not the one that autosplits.

**Comment by Calvin304** [comment]
fixed in 2476284bfb70641fae6d2341e8d3fa33f5dec8bb
